# ===============================
# CONFIGURACIÓN DEL SERVIDOR
# ===============================
server.port=${PORT:8080}

# ===============================
# CONFIGURACIÓN DE BASE DE DATOS (POSTGRESQL - SUPABASE)
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/trading_journal}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# IMPORTANTE: Cambiado a 'update' para que cree las tablas la primera vez en la nube
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# ===============================
# CONFIGURACIÓN DE SEGURIDAD (JWT)
# ===============================
application.security.jwt.secret-key=${JWT_SECRET:UnaClaveSecretaMuyLargaYSeguraParaDesarrolloLocal12345!}
application.security.jwt.expiration=86400000

# ===============================
# Google OAuth2
# ===============================
google.client.id=${GOOGLE_CLIENT_ID:62700038720-n3ght1f3hn93o39n9870undo3h3004dc.apps.googleusercontent.com}

# ===============================
# Stripe
# ===============================
stripe.api.key=${STRIPE_API_KEY:sk_test_51TRkLtEeROBBIk5suyWIeplQclHCE4sSeXF8cPN6kq6eogPlt95uzYns7Pseltu6aJJJfqHtlKI4qs3kdu5pbFKQ00lNx7YwPG}
stripe.price.pro.id=${STRIPE_PRICE_ID:price_1TRkSIEeROBBIk5sp66KZEmT}

# Redirecciones dinámicas (Usará el valor de Vercel en producción o localhost en tu PC)
stripe.success.url=${FRONTEND_URL:http://localhost:5173}/dashboard?session_id={CHECKOUT_SESSION_ID}
stripe.cancel.url=${FRONTEND_URL:http://localhost:5173}/dashboard?payment=cancelled

stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET:whsec_3dd2fa1da4230c3172e0d47cf63064c6ef927b6a55b9ca6c3d52ed4d70a221ae}

# ===============================
# CONFIGURACIÓN DE ALMACENAMIENTO (Temporal)
# ===============================
file.upload-dir=/tmp/uploads/trades
