# ===============================
# CONFIGURACIÓN DEL SERVIDOR
# ===============================
server.port=8080
spring.application.name=trading-journal

# ===============================
# CONEXIÓN A POSTGRESQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/trading_journal_db
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURACIÓN DE HIBERNATE (JPA)
# ===============================
# 'validate' asegura que las tablas en Java coincidan con las de SQL sin borrarlas
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# OBSERVABILIDAD Y MÉTRICAS (ACTUATOR)
# ===============================
management.endpoints.web.exposure.include=health,metrics
