# ===============================
# CONFIGURACIÓN DEL SERVIDOR
# ===============================
server.port=${PORT:8080}

# ===============================
# CONFIGURACIÓN DE BASE DE DATOS (POSTGRESQL - SUPABASE)
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/trading_journal}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# IMPORTANTE: Cambiado a 'update' para que cree las tablas la primera vez en la nube
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# ===============================
# CONFIGURACIÓN DE SEGURIDAD (JWT)
# ===============================
application.security.jwt.secret-key=${JWT_SECRET:UnaClaveSecretaMuyLargaYSeguraParaDesarrolloLocal12345!}
application.security.jwt.expiration=86400000

# ===============================
# Google OAuth2
# ===============================
google.client.id=${GOOGLE_CLIENT_ID:62700038720-n3ght1f3hn93o39n9870undo3h3004dc.apps.googleusercontent.com}

# ===============================
# Stripe
# ==============================
# ===============================
# CONFIGURACIÓN DE ALMACENAMIENTO (Temporal)
# ===============================
file.upload-dir=/tmp/uploads/trades
